/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindowPanel.java
 *
 * Created on 20-Jul-2010, 17:41:14
 */
package uk.ngs.certwizard.gui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.cert.X509Certificate;
import javax.swing.table.DefaultTableModel;

import uk.ngs.ca.common.SystemStatus;
import uk.ngs.ca.certificate.management.OffLineCertificateInfo;
import uk.ngs.ca.certificate.management.OnLineCertificateInfo;
import uk.ngs.ca.common.ClientKeyStore;
import uk.ngs.ca.certificate.client.CAMotd;
import uk.ngs.ca.certificate.client.CertificateDownload;
import uk.ngs.ca.certificate.client.PingService;
import uk.ngs.ca.certificate.client.RASearch;
import uk.ngs.ca.certificate.management.CertificateCSRInfo;
import uk.ngs.ca.certificate.management.RASearchInfo;
import uk.ngs.ca.certificate.management.RequestPendingInfo;
import uk.ngs.ca.common.EncryptUtil;
import uk.ngs.ca.info.CAInfo;
import uk.ngs.ca.tools.property.SysProperty;

/**
 *
 * @author xw75
 */
public class RAUtilityPanel extends javax.swing.JPanel {
    //implements Observer {

    String MotD = "Message of the Day: \n\n\nThe CA is Awesome";
    ArrayList<Certificate> array;
    private char[] PASSPHRASE;
    private OffLineCertificateInfo offLineCertInfo;
    private OnLineCertificateInfo onLineCertInfo;
    private String[] ONLINEALLDNS = null;

    private int itemSelected = -1;

    private CertificateCSRInfo[] certificateCSRInfos = null;

    private CertWizardMain _certWizardMain = null;

    private CertificateCSRInfo certificateCSRInfo = null;
    private RequestPendingInfo[] requestPendingInfos = null;

    private PrivateKey privateKey = null;
    private PublicKey publicKey = null;

    private String[] RAs = null;

    private String[] searchStatusArray = {"ALL", "VALID", "EXPIRED", "SUSPENDED", "REVOKED"};

    /** Creates new form MainWindowPanel */
    public RAUtilityPanel( CertificateCSRInfo info ){
        this.certificateCSRInfo = info;

        initComponents();

        if (SystemStatus.ISONLINE) {
            String id = info.getId();
            long long_id = new Long( id ).longValue();

            String _pswdProperty = SysProperty.getValue("uk.ngs.ca.passphrase.property");
            String _pswd = System.getProperty(_pswdProperty);
            ClientKeyStore clientKeyStore = new ClientKeyStore( _pswd.toCharArray() );
            CertificateDownload certDownload = new CertificateDownload( id );
            X509Certificate _cert = certDownload.getCertificate();
            PublicKey _publicKey = _cert.getPublicKey();
            PrivateKey _privKey = clientKeyStore.getPrivateKey(_publicKey);
            this.privateKey = _privKey;
            this.publicKey = _publicKey;

            CAInfo caInfo = new CAInfo();
            String[] _ras = caInfo.getRAs();
            int _index = _ras.length + 1;
            this.RAs = new String[ _index ];
            this.RAs[ 0 ] = "ALL";
            for( int i = 0; i < _ras.length; i++ ){
                this.RAs[ i + 1 ] = _ras[ i ];
            }
            DefaultComboBoxModel m = new DefaultComboBoxModel(RAs);
            this.searchRA.setModel(m);
            this.contactRA.setModel(m);
            m = new DefaultComboBoxModel(this.searchStatusArray);
            this.searchStatus.setModel(m);

            String _ou = _retrieveDataFromDN(this.certificateCSRInfo.getOwner(), "OU=");
            String _l = _retrieveDataFromDN(this.certificateCSRInfo.getOwner(), "L=");
            String _ra = _ou + " " + _l;
            this.searchRA.setSelectedItem(_ra);
            this.contactRA.setSelectedItem(_ra);

            CAMotd motd = new CAMotd();
            this.MotD = motd.getText();
            setMOD(this.MotD);


            this.radarIcon.setVisible(false);

        }

    }

    private String _retrieveDataFromDN(String dn, String data) {
        int index = dn.indexOf(data);
        index = index + data.length();
        String result = dn.substring(index);
        int _index = result.indexOf(",");
        if (_index != -1) {
            result = result.substring(0, _index);
        }
        result = result.trim();

        return result;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlAllDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        searchEmail = new javax.swing.JTextField();
        btnCertSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchStatus = new javax.swing.JComboBox();
        searchRA = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactName = new javax.swing.JTextField();
        contactRA = new javax.swing.JComboBox();
        btnRASearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextMOD = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        radarIcon = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("RA Utilities "));

        pnlAllDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Certificate"));

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        searchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchNameMouseExited(evt);
            }
        });

        searchEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchEmailMouseExited(evt);
            }
        });

        btnCertSearch.setText("Search");
        btnCertSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCertSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCertSearchMouseExited(evt);
            }
        });
        btnCertSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Status");

        jLabel4.setText("RA");

        searchStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchStatusMouseExited(evt);
            }
        });

        searchRA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchRAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchRAMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlAllDetailsLayout = new org.jdesktop.layout.GroupLayout(pnlAllDetails);
        pnlAllDetails.setLayout(pnlAllDetailsLayout);
        pnlAllDetailsLayout.setHorizontalGroup(
            pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAllDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlAllDetailsLayout.createSequentialGroup()
                        .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(22, 22, 22)
                        .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(searchEmail)
                            .add(searchName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                        .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(17, 17, 17)
                        .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(searchRA, 0, 262, Short.MAX_VALUE)
                            .add(searchStatus, 0, 262, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnCertSearch))
                .addContainerGap())
        );
        pnlAllDetailsLayout.setVerticalGroup(
            pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAllDetailsLayout.createSequentialGroup()
                .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(searchName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(searchStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAllDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(searchRA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCertSearch)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Request Status"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial", "CN", "OU", "L", "Status", "App. Date", "Exp. Date"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("RA Contacts"));

        jLabel5.setText("Name");

        jLabel6.setText("RA");

        contactName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactNameMouseExited(evt);
            }
        });

        contactRA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        contactRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactRAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactRAMouseExited(evt);
            }
        });

        btnRASearch.setText("Search");
        btnRASearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRASearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRASearchMouseExited(evt);
            }
        });
        btnRASearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRASearchActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel5)
                        .add(28, 28, 28)
                        .add(contactName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel6)
                        .add(34, 34, 34)
                        .add(contactRA, 0, 261, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnRASearch))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(contactName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(contactRA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnRASearch)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlAllDetails, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAllDetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        TextMOD.setColumns(20);
        TextMOD.setLineWrap(true);
        TextMOD.setRows(5);
        jScrollPane1.setViewportView(TextMOD);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/ngs/ca/images/stfc-transparent.png"))); // NOI18N

        radarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/ngs/ca/images/radar.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(radarIcon)
                        .add(48, 48, 48)))
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(radarIcon)
                        .add(18, 18, 18)
                        .add(jPanel3, 0, 298, Short.MAX_VALUE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Certificate Requests for");
    }// </editor-fold>//GEN-END:initComponents

    private boolean isPing(){
        PingService pingService = new PingService();
        return pingService.isPingService();
    }

    private void btnCertSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertSearchActionPerformed
        // TODO add your handling code here:
        if( SystemStatus.ISONLINE ){

            WaitDialog.showDialog();

            String _name = this.searchName.getText();
            String _email = this.searchEmail.getText();
            String _status = this.searchStatus.getSelectedItem().toString();
            String _ra = this.searchRA.getSelectedItem().toString();

            DefaultTableModel tModel = new DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null, null, null, null} },
                        new String [] {"Serial", "CN", "OU", "L", "Status", "App. Date", "Exp. Date"} );
            this.jTable1.setModel(tModel);

            if( _name != null ){
                _name = _name.trim();
                if( _name.equals("") ){
                    _name = null;
                }
            }
            if( _email != null ){
                _email = _email.trim();
                if( _email.equals("") ){
                    _email = null;
                }
            }

            String encodedPublicKey = EncryptUtil.getEncodedPublicKey(this.publicKey);

            RASearch raSearch = new RASearch(this.privateKey, encodedPublicKey, _name, _ra, _email, _status, null);
            if( raSearch.doGet() ){
                RASearchInfo[] infos = raSearch.getRASearchInfos();
                int index = infos.length;

                for ( int i = 0; i < index; i++ ){
                    String serialNumber = infos[ i ].getSerialNumber();
                    String cn = infos[ i ].getCN();
                    String ou = infos[ i ].getOU();
                    String l = infos[ i ].getL();
                    String status = infos[ i ].getStatus();
                    String startdate = infos[ i ].getStartDate();
                    String enddate = infos[ i ].getEndDate();
                    tModel.addRow(new Object[] {serialNumber, cn, ou, l, status, startdate, enddate} );
                }
            }else{
               JOptionPane.showMessageDialog(this, "You fail to search certificate!", "Unsuccess Search", JOptionPane.INFORMATION_MESSAGE);
            }
          
            this.radarIcon.setVisible(false);

            WaitDialog.hideDialog();
        }
 
    }//GEN-LAST:event_btnCertSearchActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void btnCertSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCertSearchMouseEntered
        // TODO add your handling code here:
        setMOD("Display selected certificate information");
    }//GEN-LAST:event_btnCertSearchMouseEntered

    private void btnCertSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCertSearchMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_btnCertSearchMouseExited

    private void btnRASearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRASearchActionPerformed
        // TODO add your handling code here:
            String _name = this.contactName.getText();
            String _ra = this.contactRA.getSelectedItem().toString();

            WaitDialog.showDialog();
            DefaultTableModel tModel = new DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null, null, null, null} },
                        new String [] {"Serial", "CN", "OU", "L", "Status", "App. Date", "Exp. Date"} );
            this.jTable1.setModel(tModel);


            if( _name != null ){
                _name = _name.trim();
                if( _name.equals("") ){
                    _name = null;
                }
            }
            String encodedPublicKey = EncryptUtil.getEncodedPublicKey(this.publicKey);

            RASearch raSearch = new RASearch(this.privateKey, encodedPublicKey, _name, _ra, null, "VALID", "RA Operator");
            if( raSearch.doGet() ){
                RASearchInfo[] infos = raSearch.getRASearchInfos();
                int index = infos.length;

                for ( int i = 0; i < index; i++ ){
                    String serialNumber = infos[ i ].getSerialNumber();
                    String cn = infos[ i ].getCN();
                    String ou = infos[ i ].getOU();
                    String l = infos[ i ].getL();
                    String status = infos[ i ].getStatus();
                    String startdate = infos[ i ].getStartDate();
                    String enddate = infos[ i ].getEndDate();
                    tModel.addRow(new Object[] {serialNumber, cn, ou, l, status, startdate, enddate} );
                }
            }else{
                JOptionPane.showMessageDialog(this, "You fail to search RA!", "Unsuccess Search", JOptionPane.INFORMATION_MESSAGE);
            }

            WaitDialog.hideDialog();
    }//GEN-LAST:event_btnRASearchActionPerformed

    private void btnRASearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRASearchMouseEntered
        // TODO add your handling code here:
        setMOD("Display selected RA's information");
    }//GEN-LAST:event_btnRASearchMouseEntered

    private void btnRASearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRASearchMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_btnRASearchMouseExited

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_jTable1MouseExited

    private void searchNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_searchNameMouseExited

    private void searchEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmailMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_searchEmailMouseExited

    private void searchStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStatusMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_searchStatusMouseExited

    private void searchRAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRAMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_searchRAMouseExited

    private void contactNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactNameMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_contactNameMouseExited

    private void contactRAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactRAMouseExited
        // TODO add your handling code here:
        if (SystemStatus.ISONLINE) {
            setMOD(MotD);
        }else{
            setRedMOD( MotD );
        }
    }//GEN-LAST:event_contactRAMouseExited

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
        setMOD("Display searched certificate information");
    }//GEN-LAST:event_jTable1MouseEntered

    private void searchNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameMouseEntered
        // TODO add your handling code here:
        setMOD("Name within the searched certificate");
    }//GEN-LAST:event_searchNameMouseEntered

    private void searchEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmailMouseEntered
        // TODO add your handling code here:
        setMOD("Email with in the searched certificate");
    }//GEN-LAST:event_searchEmailMouseEntered

    private void searchStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStatusMouseEntered
        // TODO add your handling code here:
        setMOD("Status of the searched certificate");
    }//GEN-LAST:event_searchStatusMouseEntered

    private void searchRAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRAMouseEntered
        // TODO add your handling code here:
        setMOD("RA of the searched certificate");
    }//GEN-LAST:event_searchRAMouseEntered

    private void contactNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactNameMouseEntered
        // TODO add your handling code here:
        setMOD("RA operator's name");
    }//GEN-LAST:event_contactNameMouseEntered

    private void contactRAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactRAMouseEntered
        // TODO add your handling code here:
        setMOD("Which institution of the RA Operator from");
    }//GEN-LAST:event_contactRAMouseEntered


    private void setRedMOD( String text ){
        TextMOD.setForeground(Color.RED);
        TextMOD.setText(text);
    }
    
    public void setMOD(String text) {
        TextMOD.setForeground(Color.BLACK);
        TextMOD.setText(text);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextMOD;
    private javax.swing.JButton btnCertSearch;
    private javax.swing.JButton btnRASearch;
    private javax.swing.JTextField contactName;
    private javax.swing.JComboBox contactRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlAllDetails;
    private javax.swing.JLabel radarIcon;
    private javax.swing.JTextField searchEmail;
    private javax.swing.JTextField searchName;
    private javax.swing.JComboBox searchRA;
    private javax.swing.JComboBox searchStatus;
    // End of variables declaration//GEN-END:variables
}
